"""empty message

Revision ID: 4edc25b04990
Revises: 1b966e7f4b9e
Create Date: 2016-03-29 00:54:41.346000

"""

# revision identifiers, used by Alembic.
revision = '4edc25b04990'
down_revision = '1b966e7f4b9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
